/* asbestOS -- a best OS*/

#ifndef _RTC_H
#define _RTC_H

#include "lib.h"
#include "i8259.h"


#define P1 0x70
#define P2 0x71
#define REGA 0x8A
#define REGB 0x8B
#define REGC 0x8C
#define BITMASK 0x40
#define rtc_irq_number 8


/* Handles interrupts generated by RTC */
void rtc_handler();

/* Initialize RTC */
void rtc_init();

int32_t rtc_open (const uint8_t* filename);
int32_t rtc_read (int32_t fd, void* buf, int32_t nbytes);
int32_t rtc_write (int32_t fd, const void* buf, int32_t nbytes);
int32_t rtc_close (int32_t fd);


#endif
